---
- name: Créer le namespace ArgoCD
  ansible.builtin.command:
    cmd: kubectl create namespace {{ argocd_namespace }}
  register: ns_argocd
  changed_when: "'created' in ns_argocd.stdout"
  failed_when: ns_argocd.rc != 0 and 'already exists' not in ns_argocd.stderr

- name: Créer le namespace de l'application
  ansible.builtin.command:
    cmd: kubectl create namespace {{ application_namespace }}
  register: ns_app
  changed_when: "'created' in ns_app.stdout"
  failed_when: ns_app.rc != 0 and 'already exists' not in ns_app.stderr

- name: Créer le namespace Traefik
  ansible.builtin.command:
    cmd: kubectl create namespace {{ traefik_namespace }}
  register: ns_traefik
  changed_when: "'created' in ns_traefik.stdout"
  failed_when: ns_traefik.rc != 0 and 'already exists' not in ns_traefik.stderr

- name: Créer le namespace cert-manager
  ansible.builtin.command:
    cmd: kubectl create namespace {{ cert_manager_namespace }}
  register: ns_cert_manager
  changed_when: "'created' in ns_cert_manager.stdout"
  failed_when: ns_cert_manager.rc != 0 and 'already exists' not in ns_cert_manager.stderr

- name: Créer le namespace monitoring
  ansible.builtin.command:
    cmd: kubectl create namespace {{ monitoring_namespace }}
  register: ns_monitoring
  changed_when: "'created' in ns_monitoring.stdout"
  failed_when: ns_monitoring.rc != 0 and 'already exists' not in ns_monitoring.stderr
