---
- name: Ouvrir les ports du control plane
  become: true
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_port: "{{ item }}"
    jump: ACCEPT
  loop:
    - "6443"
    - "2379:2380"
    - "10251"
    - "10252"
  when: inventory_hostname in groups['kube1']

- name: Ouvrir le port Kubelet API (10250) sur tous les noeuds
  become: true
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_port: "10250"
    jump: ACCEPT

- name: Ouvrir les ports NodePort (30000-32767) sur les workers
  become: true
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_port: "30000:32767"
    jump: ACCEPT
  when: inventory_hostname not in groups['kube1']
