---
galaxy_info:
  author: Kubequest Epitech
  description: Install kubeadm, kubelet and kubectl on Kubernetes nodes
  company: Epitech

  license: MIT

  min_ansible_version: "2.1"

  platforms:
    - name: EL
      versions:
        - all

  galaxy_tags:
    - kubernetes
    - kubeadm

dependencies: []
