---

- name: Preparation de tous les noeuds
  hosts: kube_all
  tags: preparation
  become: true
  roles:
    - docker
    - install_kubeadm

- name: Configurer le cluster Kubernetes
  hosts: kube_all
  tags: configure
  become: true
  roles:
    - configure_kubeadm

- name: Installer Helm et deployer Traefik
  hosts: kube1
  tags: traefik
  become: true
  roles:
    - install_helm
    - traefik

- name: Installer ArgoCD sur le control-plane
  hosts: kube1
  tags: argocd
  become: true
  roles:
    - argocd

- name: Installer Kyverno et ses policies de securite
  hosts: kube1
  tags: kyverno
  become: true
  roles:
    - kyverno

- name: Supprimer le cluster Kubernetes
  hosts: kube_all
  tags:
    - reset
    - never
  become: true
  roles:
    - reset_kubeadm
