---
- name: Verifier si le node a deja rejoint le cluster
  ansible.builtin.stat:
    path: /etc/kubernetes/kubelet.conf
  register: configure_kubeadm_kubelet_conf

- name: Rejoindre le cluster
  ansible.builtin.command:
    cmd: "{{ hostvars[groups['kube1'][0]].configure_kubeadm_join_command }}"
  when: not configure_kubeadm_kubelet_conf.stat.exists
  changed_when: true
