---
- name: Labeliser les nodes
  ansible.builtin.include_tasks: label_group.yml
  loop: "{{ configure_kubeadm_node_labels | dict2items }}"
  loop_control:
    label: "{{ item.key }} -> {{ item.value }}"
