---
- name: Labeliser les nodes du groupe {{ item.key }}
  ansible.builtin.include_tasks: label_group.yml
  loop: "{{ node_labels | dict2items }}"
  loop_control:
    label: "{{ item.key }} -> {{ item.value }}"

- name: Labeliser le node ingress
  ansible.builtin.command:
    cmd: >
      kubectl label node {{ hostvars[groups[ingress_node_group][ingress_node_index]]['ansible_fqdn'] }}
      node-role.kubernetes.io/{{ ingress_node_label }}= --overwrite
  changed_when: true
