---
- name: Apply node taint  # noqa: name[template]
  ansible.builtin.command:
    cmd: kubectl taint nodes {{ hostvars[node]['ansible_fqdn'] }} {{ item.value }} --overwrite
  loop: "{{ configure_kubeadm_node_taints | dict2items }}"
  loop_control:
    label: "{{ item.key }} -> {{ item.value }}"
  vars:
    node: "{{ groups[item.key][0] }}"
  changed_when: true
